// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// display_char //
// ------------ //

#define display_char_wrap_target 1
#define display_char_wrap 5

static const uint16_t display_char_program_instructions[] = {
    0xbf42, //  0: nop                    side 1 [15]
            //     .wrap_target
    0xd026, //  1: irq    wait 6          side 1     
    0x7008, //  2: out    pins, 8         side 1     
    0xaa42, //  3: nop                    side 0 [10]
    0xba42, //  4: nop                    side 1 [10]
    0xd026, //  5: irq    wait 6          side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program display_char_program = {
    .instructions = display_char_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config display_char_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + display_char_wrap_target, offset + display_char_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ------------ //
// set_char_pos //
// ------------ //

#define set_char_pos_wrap_target 0
#define set_char_pos_wrap 7

static const uint16_t set_char_pos_program_instructions[] = {
            //     .wrap_target
    0xc027, //  0: irq    wait 7                     
    0xe023, //  1: set    x, 3                       
    0xa001, //  2: mov    pins, x                    
    0xa742, //  3: nop                           [7] 
    0x20c6, //  4: wait   1 irq, 6                   
    0x20c6, //  5: wait   1 irq, 6                   
    0x0042, //  6: jmp    x--, 2                     
    0xc027, //  7: irq    wait 7                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program set_char_pos_program = {
    .instructions = set_char_pos_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config set_char_pos_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + set_char_pos_wrap_target, offset + set_char_pos_wrap);
    return c;
}
#endif

// -------------- //
// select_display //
// -------------- //

#define select_display_wrap_target 0
#define select_display_wrap 8

static const uint16_t select_display_program_instructions[] = {
            //     .wrap_target
    0xe020, //  0: set    x, 0                       
    0xa001, //  1: mov    pins, x                    
    0xa049, //  2: mov    y, !x                      
    0x0084, //  3: jmp    y--, 4                     
    0xa02a, //  4: mov    x, !y                      
    0x20c7, //  5: wait   1 irq, 7                   
    0x20c7, //  6: wait   1 irq, 7                   
    0xe04a, //  7: set    y, 10                      
    0x00a1, //  8: jmp    x != y, 1                  
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program select_display_program = {
    .instructions = select_display_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config select_display_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + select_display_wrap_target, offset + select_display_wrap);
    return c;
}

#include "hardware/clocks.h"
#define MDL2416C_DATA_PINS_NUM  7 
#define MDL2416C_ADDR_PINS_NUM  2
#define MDL2416C_PIO_DISPLAY_CHAR_SM   0
#define MDL2416C_PIO_SET_CHAR_POS_SM   1
#define MDL2416C_PIO_SELECT_DISPLAY_SM 2
static inline void mdl2416c_program_init(PIO pio, uint data_pins_base,
                                         uint addr_pins_base,
                                         uint ce_pins_base, uint ce_pins_num,
                                         uint write_pin)
{
    uint8_t i;
    for (i = 0; i < MDL2416C_DATA_PINS_NUM; i++)
    {
        pio_gpio_init(pio, data_pins_base + i);
    }
    for (i = 0; i < MDL2416C_ADDR_PINS_NUM; i++)
    {
        pio_gpio_init(pio, addr_pins_base + i);
    }
    for (i = 0; i < ce_pins_num; i++)
    {
        pio_gpio_init(pio, ce_pins_base + i);
    }
    pio_gpio_init(pio, write_pin);
    pio_sm_set_consecutive_pindirs(pio, MDL2416C_PIO_DISPLAY_CHAR_SM,
                                   data_pins_base, MDL2416C_DATA_PINS_NUM,
                                   true);
    pio_sm_set_consecutive_pindirs(pio, MDL2416C_PIO_DISPLAY_CHAR_SM,
                                   write_pin, 1, true);
    pio_sm_set_consecutive_pindirs(pio, MDL2416C_PIO_SET_CHAR_POS_SM,
                                   addr_pins_base, MDL2416C_ADDR_PINS_NUM,
                                   true);
    pio_sm_set_consecutive_pindirs(pio, MDL2416C_PIO_SELECT_DISPLAY_SM,
                                   ce_pins_base, ce_pins_num,
                                   true);
    pio_sm_config c;
    uint offs0 = pio_add_program(pio, &display_char_program);
    c = display_char_program_get_default_config(offs0);
    sm_config_set_out_shift(&c, false, true, 8);
    sm_config_set_out_pins(&c, data_pins_base, MDL2416C_DATA_PINS_NUM);
    sm_config_set_sideset_pins(&c, write_pin);
    sm_config_set_clkdiv(&c, 100.0);
    pio_sm_init(pio, MDL2416C_PIO_DISPLAY_CHAR_SM, offs0, &c);
    uint offs1 = pio_add_program(pio, &set_char_pos_program);
    c = set_char_pos_program_get_default_config(offs1);
    sm_config_set_out_shift(&c, false, false, 32);
    sm_config_set_out_pins(&c, addr_pins_base, MDL2416C_ADDR_PINS_NUM);
    sm_config_set_clkdiv(&c, 100.0);
    pio_sm_init(pio, MDL2416C_PIO_SET_CHAR_POS_SM, offs1, &c);
    uint offs2 = pio_add_program(pio, &select_display_program);
    c = select_display_program_get_default_config(offs2);
    sm_config_set_out_shift(&c, false, true, 32);
    sm_config_set_out_pins(&c, ce_pins_base, ce_pins_num);
    sm_config_set_clkdiv(&c, 10.0);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    pio_sm_init(pio, MDL2416C_PIO_SELECT_DISPLAY_SM, offs2, &c);
    pio_set_sm_mask_enabled(pio, 0x07, true);
}

#endif

